import {
    Texture,
} from "pixi.js";

import { FIRE_ART_DIRECTION } from "../config/FireArtDirectionDefinition";

import {
    AssetLoader,
} from "../../rendering/AssetLoader";

export interface FireVfxMainTextures {
    readonly hot:
    Texture;

    readonly body:
    Texture;

    readonly cool:
    Texture;
}

export interface FireVfxDetailTextures {
    readonly hot:
    readonly Texture[];

    readonly body:
    readonly Texture[];

    readonly cool:
    readonly Texture[];
}

export interface FireVfxTextures {
    readonly main:
    FireVfxMainTextures;

    readonly detail:
    FireVfxDetailTextures;

    readonly ember:
    Texture;
}

/**
 * FIRE-VFX-CRISP-1A texture factory.
 *
 * Presentation-only experiment:
 *
 * - Fire simulation/gameplay is untouched.
 * - GroundFireEmitter and JetFireEmitter are untouched.
 * - Existing Fire noise generation is bypassed for active flame particles.
 * - Legacy soft masks remain loaded and available for fallback.
 * - HOT / BODY / COOL continue to use the existing thermal-role tint system.
 *
 * Main mappings provide deterministic fallbacks.
 * Detail mappings are direct crisp-mask pools. They are AssetLoader-owned
 * textures, not generated textures.
 */
export class FireVfxTextureFactory {

    public static create():
        FireVfxTextures {
        const palette = FIRE_ART_DIRECTION.palette;
        if (
            !Number.isFinite(palette.hotCore) ||
            !Number.isFinite(palette.hot) ||
            !Number.isFinite(palette.body) ||
            !Number.isFinite(palette.coolOuter)
        ) {
            throw new Error("Invalid shared Fire art-direction palette.");
        }


        const main:
            FireVfxMainTextures = {

            hot:
                AssetLoader.getTexture(
                    "fireFlameSmall",
                ),

            body:
                AssetLoader.getTexture(
                    "fireFlameBroad",
                ),

            cool:
                AssetLoader.getTexture(
                    "fireFlameBroad",
                ),
        };

        const detail:
            FireVfxDetailTextures = {

            hot: [
                AssetLoader.getTexture(
                    "fireFlameSmall",
                ),
                AssetLoader.getTexture(
                    "fireFlameTall",
                ),
                AssetLoader.getTexture(
                    "fireFlameCurveLeft",
                ),
                AssetLoader.getTexture(
                    "fireFlameCurveRight",
                ),
            ],

            body: [
                AssetLoader.getTexture(
                    "fireFlameBroad",
                ),
                AssetLoader.getTexture(
                    "fireFlameTall",
                ),
                AssetLoader.getTexture(
                    "fireFlameCurveLeft",
                ),
                AssetLoader.getTexture(
                    "fireFlameCurveRight",
                ),
                AssetLoader.getTexture(
                    "fireFlameFork",
                ),
            ],

            cool: [
                AssetLoader.getTexture(
                    "fireFlameBroad",
                ),
                AssetLoader.getTexture(
                    "fireFlameCurveLeft",
                ),
                AssetLoader.getTexture(
                    "fireFlameCurveRight",
                ),
                AssetLoader.getTexture(
                    "fireFlameFork",
                ),
            ],
        };

        return {
            main,
            detail,

            // Ember presentation is intentionally unchanged in 1A.
            ember:
                AssetLoader.getTexture(
                    "fireGlowRound",
                ),
        };
    }

    public static destroy(
        _textures:
            FireVfxTextures,
    ): void {

        /*
         * FIRE-VFX-CRISP-1A uses only AssetLoader-owned textures.
         * Nothing is generated by this factory.
         */
    }
}
